[config]
schemaVersion = "0.0.1"

[package]
namespace = "deB"
name = "Debbys_Case"
versionNumber = "0.0.1"
description = "Adds various content supposed to fit the vibe of REPO"
websiteUrl = "https://github.com/TheDebbyCase/REPODebbysCase"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Zehs-REPOLib = "2.1.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "."

[[build.copy]]
source = "./Debbys Case/Builds/netstandard2.1/REPODebbyCase.dll"
target = "BepInEx/plugins/Debbys Case/REPODebbyCase.dll"

[[build.copy]]
source = "./Debbys Case/Builds/debbycase"
target = "BepInEx/plugins/Debbys Case/debbycase"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[publish]
communities = ["repo"]
[publish.categories]
repo = ["mods", "monsters", "serverside", "clientside"]


